##################################################################
# Compile cenviron.c into cenviron.dll--a shareable object file 
# on Cygwin, which is loaded dynamically when first imported. 
##################################################################

PYLIB = /usr/bin
PYINC = /usr/include/python2.4

cenviron.dll: cenviron.c
	gcc cenviron.c -g -I$(PYINC) -shared  -L$(PYLIB) -lpython2.4 -o $@

clean:
	rm -f *.pyc cenviron.dll
