#!c:/python23/python.exe
import cgi, cgitb, os, sys, string, time
cgitb.enable()

def gush(data):
    print """Content-type: text/html\n
<h3>Thanks, %(name)s!</h3>
Our customer's comments are always appreciated.
They drive our business directions, as well as
help us with our karma.
<p>Thanks again for the feedback!<p>
And feel free to enter more comments if you wish.""" % vars(data)
    print "<p>"+10*"&nbsp;"+"--Joe."

def whimper(data):
    print """Content-type: text/html\n
<h3>Sorry, %(name)s!</h3>
We're very sorry to read that you had a complaint"
regarding our product__We'll read your comments"
carefully and will be in touch with you."
<p>Nevertheless, thanks for the feedback.<p>""" % vars(data)
    print "<p>"+10*"&nbsp;"+"--Joe."

def bail():
    print """<h3>Error filling out form</h3>
Please fill in all the fields in the form.<p>
<a href="http://localhost/comment.html">
Go back to the form</a>"""
    sys.exit()

class FormData:
    """ A repository for information gleaned from a CGI form """
    def __init__(self, form):
        self.time = time.asctime()
        for fieldname in self.fieldnames:
            if fieldname not in form or form[fieldname].value == "":
                bail()
            else:
                setattr(self, fieldname, form[fieldname].value)
       
class FeedbackData(FormData):
    """ A FormData generated by the comment.html form. """
    fieldnames = ('name', 'address', 'email', 'type', 'text')
    def __repr__(self):
        return "%(type)s from %(name)s on %(time)s" % vars(self)

DIRECTORY = r'C:\complaintdir'

if __name__ == '__main__':
    sys.stderr = sys.stdout 
    form = cgi.FieldStorage()
    data = FeedbackData(form)
    if data.type == 'comment':
        gush(data)
    else:
        whimper(data)

    # save the data to file
    import tempfile, pickle
    tempfile.tempdir = DIRECTORY
    pickle.dump(data, open(tempfile.mktemp(), 'w'))
